modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="scb"
version="1.0.0"
displayName="Simple Command Blocks"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Mikki, ShaneMarks on MCreator 2020"

[[dependencies.scb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



