modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="simple_command_blocks"
version="1.0.0"
displayName="Simple Command Blocks"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Maks, MCreator"

[[dependencies.simple_command_blocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



